export const TOP = '/'
export const DISCLAIMER = '/disclaimer'
export const TEAM_DEVELOPERS = '/team/developers'
export const TEAM_DESIGNERS = '/team/designers'
export const TEAM_INVESTORS = '/team/investors'
export const TEAM_PROMOTERS = '/team/promoters'
