export const TOP = '/'
export const DISCLAIMER = '/disclaimer'
export const TEAM_DEVELOPERS = '/team/developers'
export const TEAM_DESIGNERS = '/team/designers'
export const TEAM_INVESTORS = '/team/investors'
export const TEAM_PROMOTERS = '/team/promoters'

export const APP = '/app'
export const APP_STAKE = '/app/stake'
export const APP_RESTAKE = '/app/restake'
export const APP_CLAIM = '/app/claim'

export const DISCORD_INVITATION_URL = 'https://discord.gg/Mf9zsXRnaX'
export const METAMASK_URL = 'https://metamask.io/'
export const ETHERSCAN_URL = 'https://etherscan.io/'
